;; font setting
(when (and (boundp 'window-system)
           window-system
           (fboundp 'set-fontset-font))
  (set-frame-font "Panic Sans-12")
  ;;(set-frame-font "Andale Mono-13")
  (set-fontset-font (frame-parameter nil 'font)
                    'han '("STHeiti" . "ISO10646-1"))
  (set-fontset-font (frame-parameter nil 'font)
                    'symbol '("STHeiti" . "ISO10646-1"))
  (set-fontset-font (frame-parameter nil 'font)
                    'cjk-misc '("STHeiti" . "ISO10646-1"))
  (set-fontset-font (frame-parameter nil 'font)
                    'bopomofo '("STHeiti" . "ISO10646-1"))
  )

(when (and (boundp 'window-system)
           window-system
           (fboundp 'set-fontset-font))
  (set-frame-font "Anonymous Pro:pixelsize=20:antialias=subpixel")
  ;;(set-frame-font "Andale Mono-13")
  (let ((fontset "fontset-default"))
    (dolist (charset '(han symbol cjk-misc bopomofo kana hangul))
      (set-fontset-font (frame-parameter nil 'font)
                        charset
                        (font-spec :family "Hiragino Sans GB" :size 20)
      )))
  ;; (set-fontset-font (frame-parameter nil 'font)
  ;;                   'han '("STHeiti" . "ISO10646-1"))
  ;; (set-fontset-font (frame-parameter nil 'font)
  ;;                   'symbol '("STHeiti" . "ISO10646-1"))
  ;; (set-fontset-font (frame-parameter nil 'font)
  ;;                   'cjk-misc '("STHeiti" . "ISO10646-1"))
  ;; (set-fontset-font (frame-parameter nil 'font)
  ;;                   'bopomofo '("STHeiti" . "ISO10646-1"))
  )

;; font settings:
;;(set-default-font "DejaVu Sans Mono-12")
;;(set-default-font "Monaco-12")
;;(set-default-font "Lucida Console-12")
;;(set-default-font "Anonymous-11")
;;(set-default-font "Consolas-13")

(add-to-list 'after-make-frame-functions
             (lambda (new-frame)
               (select-frame new-frame)
               (when (and (fboundp 'w32-maximize-frame) (eq 'windows-nt system-type))
                 (w32-maximize-frame))
               (when (and (boundp 'window-system)
                          window-system
                          (fboundp 'set-fontset-font))
                 (set-frame-font "Dejavu Sans Mono:pixelsize=14:antialias=subpixel")
                 (let ((fontset (frame-parameter new-frame 'font)))
                   (dolist (charset '(han symbol cjk-misc bopomofo))
                     (set-fontset-font fontset charset '("YaHei consolas Hybrid" . "unicode-bmp"))))
                 ;; (set-fontset-font (frame-parameter new-frame 'font)
;;                                    'han '("YaHei Consolas Hybrid" . "unicode-bmp"))
;;                  (set-fontset-font (frame-parameter new-frame 'font)
;;                                    'symbol '("YaHei Consolas Hybrid" . "unicode-bmp"))
;;                  (set-fontset-font (frame-parameter new-frame 'font)
;;                                    'cjk-misc '("YaHei Consolas Hybrid" . "unicode-bmp"))
;;                  (set-fontset-font (frame-parameter new-frame 'font)
;;                                    'bopomofo '("YaHei Consolas Hybrid" . "unicode-bmp"))
                 )))
