(global-set-key "\M-'" 'mark-sexp)
(global-set-key (kbd "C-.") 'set-mark-command)
;;(global-set-key "\M-s" 'search-forward-regexp)
(global-set-key [deletechar] 'delete-backward-char)
(global-set-key [delete] 'delete-char)
(global-set-key [kp-delete] 'delete-char)
(global-set-key (kbd "<C-return>") 'hippie-expand)
;;(global-set-key (kbd "C-;") 'set-mark-command)
(global-set-key [(control \;)] 'set-mark-command)
(global-set-key (kbd "C-2") 'set-mark-command)
(global-set-key [f12] 'shell)
(global-set-key [f9] 'list-bookmarks)
(global-set-key [f8] 'goto-line)
;;(global-set-key "\C-x\C-b" 'bs-show) ;;or 'electric-buffer-list
(global-set-key [(f3)] 'remember)
(global-set-key [(f7)] 'manual-entry)
(global-set-key [(f2)] 'planner-create-task)
(global-set-key [(f5)] 'cl-info)
;;(global-set-key (kbd "<F9> t") 'planner-create-task-from-buffer)
;;(global-set-key [(f4)] 'manual-entry)
(global-set-key [(f4)] 'planner-goto-most-recent)
(global-set-key [(f9)] 'compile)
;;(global-set-key [(f5)] 'joc-dired-magic-buffer)
(global-set-key [(meta f5)] 'joc-dired-toggle-buffer-name)
(global-set-key [(control f5)] (function
                                (lambda nil (interactive)
                                  (joc-dired-magic-buffer default-directory))))
(global-set-key [(shift f5)] (function
                              (lambda nil (interactive)
                                (message "Current directory is: %s" default-directory))))
(global-set-key "\C-x\C-m" 'execute-extended-command)
(global-set-key (kbd "C-x m") 'execute-extended-command)
;;(global-set-key "\C-c\C-m" 'execute-extended-command)
(global-set-key "\C-h" 'delete-backward-char)
(global-set-key "\C-w"     'my-kill-ring-save-or-kill-word)
(global-set-key "\C-x\C-k" 'kill-region)
(global-set-key "\C-c\C-k" 'kill-region)
(global-set-key (kbd "C-x C-2") 'clone-indirect-buffer)
(global-set-key (kbd "\e\el") 'goto-line)
(global-set-key "\C-m" 'newline-and-indent)

(global-set-key "\M-&" 'query-replace-regexp)
(global-set-key (kbd "C-2") 'set-mark-command)
;;(global-set-key "\C-c\C-m" 'set-mark-command)

;; Set up the keyboard so the delete key on both the regular keyboard
;; and the keypad delete the character under the cursor and to the right
;; under X, instead of the default, backspace behavior.
(global-set-key [delete] 'delete-char)
(global-set-key [kp-delete] 'delete-char)
(global-set-key (kbd "ESC <deletechar>") 'backward-kill-word)

(global-unset-key (kbd "C-SPC"))
(global-unset-key "\C-x\C-c")
(global-unset-key "\C-z")
